데이터 준비하기

In [1]:
from sklearn.datasets import load_iris
import numpy as np

iris = load_iris() # iris 데이터 불러오기
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [2]:
print('iris 데이터의 형태:', iris.data.shape)
print('iris 데이터의 속성들:', iris.feature_names)
print('iris 데이터의 레이블:', iris.target)

iris 데이터의 형태: (150, 4)
iris 데이터의 속성들: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
iris 데이터의 레이블: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [3]:
from sklearn.model_selection import train_test_split
X,y = iris.data, iris.target
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3) # 붓꼬데이터를 70%를 학습, 30% 테스트 데이터 분리

In [4]:
#데이터 표준화(standardization)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() 
SX_train = scaler.fit_transform(X_train)
SX_test = scaler.fit_transform(X_test)

- K-NN (K=5)

In [5]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

k = 5

knn = KNeighborsClassifier(n_neighbors= k)
knn.fit(SX_train, y_train)

y_pred = knn.predict(SX_test)
knn_matrix = confusion_matrix(y_test, y_pred)
Knn_accuracy = metrics.accuracy_score(y_test, y_pred)
print('n_neighbors가 {0:d} 일때 Knn 모델의 정확도: {1:.3f}\n'.format(k,Knn_accuracy))
print('Knn confusion_matrix:')
print(knn_matrix)

n_neighbors가 5 일때 Knn 모델의 정확도: 0.911

Knn confusion_matrix:
[[16  1  0]
 [ 0 10  0]
 [ 0  3 15]]


- Logistic Regression

In [6]:
from sklearn.linear_model import LogisticRegression

LogisticRegression_model = LogisticRegression(max_iter=500)
LogisticRegression_model.fit(SX_train, y_train)

y_pred = LogisticRegression_model.predict(SX_test)
LogisticRegression_accuracy = metrics.accuracy_score(y_test, y_pred)
LogisticRegression_matrix = confusion_matrix(y_test, y_pred)
print('Logistic_Regression의 정확도: {:.3f}\n'.format(LogisticRegression_accuracy))
print('LogisticRegression confusion_matrix:')
print(LogisticRegression_matrix)



Logistic_Regression의 정확도: 0.933

LogisticRegression confusion_matrix:
[[16  1  0]
 [ 0 10  0]
 [ 0  2 16]]


- Decision-Tree : max_depth = 4, criterion = gini

In [7]:
from sklearn.tree import DecisionTreeClassifier
dec_tree = DecisionTreeClassifier(max_depth=4, criterion='gini')
dec_tree.fit(SX_train, y_train)

y_pred = dec_tree.predict(SX_test)
dec_tree_accuracy = accuracy_score(y_test, y_pred)
dec_tree_matrix = confusion_matrix(y_test, y_pred)
print('Decision Tree 1 의 정확도: {:.3f}\n'.format(dec_tree_accuracy))
print('Decision Tree 1 confusion_matrix:')
print(dec_tree_matrix )

Decision Tree 1 의 정확도: 0.933

Decision Tree 1 confusion_matrix:
[[17  0  0]
 [ 0 10  0]
 [ 0  3 15]]


- Decision-Tree : max_depth = 4, criterion = entropy



In [8]:
from sklearn.tree import DecisionTreeClassifier
dec_tree_2 = DecisionTreeClassifier(max_depth=4, criterion='entropy')
dec_tree_2.fit(SX_train, y_train)

y_pred = dec_tree_2.predict(SX_test)
dec_tree_2_accuracy = accuracy_score(y_test, y_pred)
dec_tree_2_matrix = confusion_matrix(y_test, y_pred)
print('Decision Tree 2 의 정확도: {:.3f}\n'.format(dec_tree_2_accuracy))
print('Decision Tree 2 confusion_matrix:')
print(dec_tree_2_matrix )

Decision Tree 2 의 정확도: 0.933

Decision Tree 2 confusion_matrix:
[[17  0  0]
 [ 0 10  0]
 [ 0  3 15]]


- LinerSVM

In [9]:
from sklearn.svm import LinearSVC
svm_simple = LinearSVC(max_iter=10000)
svm_simple.fit(SX_train, y_train)

y_pred = svm_simple.predict(SX_test)
svm_simple_accuracy = accuracy_score(y_test, y_pred)
svm_simple_matrix = confusion_matrix(y_test, y_pred)
print('Decision Tree 2 의 정확도: {:.3f}\n'.format(svm_simple_accuracy))
print('Decision Tree 2 confusion_matrix:')
print(svm_simple_matrix )

Decision Tree 2 의 정확도: 0.889

Decision Tree 2 confusion_matrix:
[[16  1  0]
 [ 0  9  1]
 [ 0  3 15]]


- 앙상블

In [10]:
from sklearn.ensemble import VotingClassifier

voting_model = VotingClassifier(
    estimators=[('knn', knn), 
                ('LogisticRegression', LogisticRegression_model), 
                ('dec_tree_1', dec_tree), 
                ('dec_tree_2', dec_tree_2), 
                ('svm', svm_simple)], 
    voting='hard')

voting_model.fit(SX_train, y_train)
y_pred = voting_model.predict(SX_test)

voting_model_accuracy = accuracy_score(y_test, y_pred)
print("앙상블의 정확도: {:.3f}".format(voting_model_accuracy))

앙상블의 정확도: 0.911
